version: "3"

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gitstar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: .
    command: sh -c "pnpm prisma migrate dev"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - postgres-db
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker1:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=1
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  worker2:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=2
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  worker3:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=3
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  worker4:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=4
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  worker5:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=5
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  worker6:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=6
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  worker7:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=7
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  worker8:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=8
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

volumes:
  postgres_data:
