version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"  

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 4
