version: "3"

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gitstar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: .
    command: sh -c "pnpm prisma migrate dev"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - postgres-db
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker1:
    build: .
    command: sh -c "pnpm worker"
    environment:
      - WORKER_ID=1
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/gitstar
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app

  app:
    build: .
    command: sh -c "pnpm run start"
    depends_on:
      - postgres-db
      - redis
      - migrate
      - worker1
    volumes:
      - .:/app

volumes:
  postgres_data:
